version '3.8'

services:
  database:
    build:
      context: ./mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: titanic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  python:
    build:
      context: ./python
    container_name: python
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: titanic
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "5000:5000"


  web:
    build:
      context: ./web
    container_name: web
    depends_on:
      - python
    ports:
      - "8080:80"
